# Uncomment the next line to define a global platform for your project
platform :ios, "9.0"
inhibit_all_warnings!

target 'ZYBS' do
    
    pod "AFNetworking"
    pod "SDWebImage"
    pod "MJExtension"
    pod "SVProgressHUD"
    pod "MJRefresh"
    pod "DACircularProgress"
end
